# Generated by Django 4.0.3 on 2022-03-17 23:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=64)),
                ('categoryDescription', models.TextField()),
                ('categoryCreateDate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortDescription', models.CharField(max_length=64)),
                ('CompleteDescription', models.TextField()),
                ('Category', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, related_name='ItensPerCategory', to='auctions.category')),
                ('User', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ItemsPerCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
